### PR TITLE
Use AMGX_jll 2.3 and bump julia compat to 1.6

### PR DESCRIPTION
**Pull request by vchuravy**

### CODE REVIEW

**Comment by vchuravy** [comment]
In conversation with @maleadt we should yank the previous release since it falsly promises compat with CUDA@4.

**Comment by moyner** [comment]
Hi! Any interest in updating this? The JLL is already built. I guess the latest AMGX 2.4.0 https://github.com/NVIDIA/AMGX/releases/tag/v2.4.0 would also be nice to have - then CUDA 12 is supported and it would be possible to use AMGX in later Julia versions from what I gather.

**Comment by maleadt** [comment]
I don't think any of us is using AGMX.jl right now, so your best bet is to look into this yourself. Feel free to reach out if you have any issues though. For support with AMGX v2.4, you'd need to update the build recipe here: https://github.com/JuliaPackaging/Yggdrasil/blob/master/A/AMGX/build_tarballs.jl

**Comment by moyner** [comment]
> I don't think any of us is using AGMX.jl right now, so your best bet is to look into this yourself. Feel free to reach out if you have any issues though. For support with AMGX v2.4, you'd need to update the build recipe here: https://github.com/JuliaPackaging/Yggdrasil/blob/master/A/AMGX/build_tarballs.jl

Thanks! I'm having a go at this. I tried updating the script to the latest release, but I ended up stuck at messages of the type `cuda_architectures is empty for target xxx.`  where xxx would  be for example `cmtc_d1232`. If I try the original build script I see that the same happens for the unmodified script if I change the CUDA versions to be what is currently supported in BinaryBuilder's cuda.jl.

I can build the AMGX binaries without issue with CMake outside of Julia, but I'm having some difficulty understanding how to get it to build from within the Julia script. Am I supposed to target the latest CUDA? Can I do that since BB needs Julia 1.7 and not later? I think the changes in AMGX are not too large to handle, but I'd ideally have a baseline build of the old binaries to start from.

**Comment by maleadt** [comment]
I'll update the build recipe.

**Comment by maleadt** [comment]
https://github.com/JuliaPackaging/Yggdrasil/pull/9657

**Comment by moyner** [comment]
Thanks a lot - I will try to make a PR that updates AMGX.jl to use the new JLL and latest versions based off this PR unless anyone else is already doing it.

**Pull request closed without merging**
